### ISSUE TITLE
[suggestion] more villager types

### ISSUE THREAD

**Issue by krispyking24** [maxsupermanhd/meteor-villager-roller#13]
there's more types of villagers then just the librarian maybe add the other types of villagers and their trades

**Comment by maxsupermanhd** [comment]
Example? What villager requires **rolling** of trades?

**Comment by krispyking24** [comment]
an example would be farmer trades for emerald trading

**Comment by maxsupermanhd** [comment]
I don't understand you, so you saying you need to **roll trades** for "farmer trades for emerald trading"? Toolsmith and armorer require one level up for an iron trade, don't see how it can be rolled.

Let me clarify again, this addon is designed to roll for enchanted books since they can require huge time investments for one roll/villager. This is not a "auto everything-trading hall addon", you will have to roll primitive trades and move villagers around by yourself, if you are too lazy for that I am genuinely curious how you after opening the game, installing both meteor and roller addon not dead from boredom and laziness.
