### ISSUE TITLE
Update to 1.20.1

### ISSUE THREAD

**Issue by Ebanytiy** [maxsupermanhd/meteor-villager-roller#25]
meteor client updated to 1.20

**Comment by maxsupermanhd** [comment]
I could update to 1.20 but I would like to test that nothing broke and for that I need a 1.20 server where I can use roller (bonus for not being banned)

Or I could just bump the version and hope that it works...

For now I would like to wait until some servers update.

**Comment by JACKKY04** [comment]
Why not just host your own for testing? 1.20 Paper is out.

**Comment by maxsupermanhd** [comment]
Because I am lazy ass

**Comment by JACKKY04** [comment]
> Because I am lazy ass

Fairs

**Comment by JACKKY04** [comment]
1.20.1 XD

**Comment by Yosirgen** [comment]
wait for 1.20.1

**Comment by JACKKY04** [comment]
> wait for 1.20.1

Already got it lol

**Comment by rekitrelt** [comment]
https://cdn.discordapp.com/attachments/1044584879922360342/1120392497684807750/villager-roller-1.3.10mc1.20.1-rev.e33a03d-dirty.jar
MaX the owner in the discord ^

**Comment by maxsupermanhd** [comment]
Very disrespectful to not only post testing versions here where they were meant for only one individual on the discord but also not providing any feedback on how it works.

**Comment by rekitrelt** [comment]
> Very disrespectful to not only post testing versions here where they were meant for only one individual on the discord but also not providing any feedback on how it works.

I'm sorry, I haven't gotten much of a chance to try it, I only found the same glitch that the person on the discord found where you can't save config

**Comment by Darkcarnage23** [comment]
I tried out v1.4.2 for 1.20.1 on a paper server and it works pretty fine. Also tried it with an anticheat (vulcan) just in case and no issues.

might be something on my end but i sometimes get a flicker of the trading gui which i never really gotten in the older versions but its not annoying.

Config saving works and it persists after rejoining server/restarting mc

**Comment by maxsupermanhd** [comment]
tf why this issue is open

Re @Darkcarnage23
Flicker of the trade menu is *by design*. I know it is theoretically possible to intercept a screen opening but that's a rabbit hole I don't think worth a time waste. When module is active and in the stage points towards interacting with villager client will literally execute right click on the entity and wait for actual screen to be opened and trades to be received.
It is painful because you can't chat while rolling but oh well I can't figure how to avoid it properly so I don't have to rewrite everything every version.

Also did Vulcan detect anything? Like in server console or whatever it uses to store violations. Also it depends on the setup (block, villager and player positioning) and I would actually expect that most anticheats will at least detect it like some bot behavior.

**Comment by Darkcarnage23** [comment]
yeah i wasnt sure if you needed the reply but was like hey this addon was useful and the least i could do was test it. Yeah Vulcan didnt flag it all. It does flag baritone but for some reason it hasnt flagged the roller. I think they/some AC arent specifically looking out for it
