### ISSUE TITLE
[suggestion]Add a button to turn off information prompts

### ISSUE THREAD

**Issue by Mrorik1** [maxsupermanhd/meteor-villager-roller#42]
When I use this mod to refresh the villagers, even if I obtain an unexpected enchantment, it will still pop up a bunch of useless information in the bottom left corner. Can a button be added for players to freely choose whether to pop up irrelevant information?

**Comment by maxsupermanhd** [comment]
Alright, I was waiting for someone to actually be annoyed enough to come here and open an issue about it. Since you clearly really want this feature then you will be willing to test it out for me because I am a lazy person.

[villager-roller-1.4.8+mc1.21.1-rev.5443bc0.zip](https://github.com/user-attachments/files/17784315/villager-roller-1.4.8%2Bmc1.21.1-rev.5443bc0.zip) (file extension changed to .zip due to github, rename to .jar after downloading)

Here is a build of roller that has chat feedback toggles section in settings. Please verify that everything works as expected and all toggles function as they should as well as if there are any messages I missed.

Once you confirm that everything works as expected I will push it to master and bump the version.

**Comment by Mrorik1** [comment]
I'm sorry, but in fact, I'm using version 1.21 and I recompiled the version I need from your source code two days ago. I'm sorry I forgot to check the ISSUES information

**Comment by maxsupermanhd** [comment]
Implemented in latest version, I am not backporting it
