### ISSUE TITLE
[Suggestions] Automatically fetch lowest price for each enchantment based on selected level

### ISSUE THREAD

**Issue by Lovecrafts-Cat** [maxsupermanhd/meteor-villager-roller#6]
Based on the Minecraft Wiki:
> The price in emeralds depends on the enchantment level and "treasure" status.
> The possible values are:
> - 5–19 emeralds for Lvl I,
> - 8–32 for Lvl II,
> - 11–45 for Lvl III,
> - 14–58 for Lvl IV,
> - 17–71 for Lvl V.

> For [treasure enchantments](https://minecraft.fandom.com/wiki/Treasure_enchantment) the price is doubled.
> Note that the cost is capped to 64, meaning that for example Lvl V books truly range from 17–64 emeralds.

It would be nice if there was an option/button that would add all enchantments with MAX level and MIN cost.
Could either be a profile already bundled with the addon, or implemented in any other way.

**Comment by maxsupermanhd** [comment]
Huh, I didn't knew about such thing existing, I thought they are genuinely random.

Well in this case maybe it is a good idea to set price based on minimum + 1 because I remember there is a method to get both treasure and level parameters.

However do note - thing is made flexible so servers can tweak this too, sometimes it might be lower than minimum prices if plugins/mods are set up incorrectly. Because of this I will leave max/min field limits the same (1, 64).

**Comment by maxsupermanhd** [comment]
Done, added a button near cost to set it to min cost and default to minim cost and max level when adding new enchantment. Also sorted enchantment selection screen by name. Please report any issues, dev build should be available soon.

**Comment by Lovecrafts-Cat** [comment]
All looks good as of now, really appreciate this 👍
