### ISSUE TITLE
Its outdated for the latest release of meteor

### ISSUE THREAD

**Issue by 60YzArC** [maxsupermanhd/meteor-villager-roller#9]
update. pls and thank you

:)

**Comment by Lovecrafts-Cat** [comment]
![image](https://user-images.githubusercontent.com/52252627/180624202-3a1b0ba5-029f-41d2-aeb4-4bcc7bab0e2a.png)
![image](https://user-images.githubusercontent.com/52252627/180624217-cf4a1dc4-c2a1-4b85-b801-314da85ae8fe.png)

Here's the messages describing the new changes needed to make this work from 1.19 onwards.
Hope this can help you prepare a ne release of this amazing addon 👍.

**Comment by maxsupermanhd** [comment]
Until there is a reason to update to further snapshots it will remain as it is. I see no point of fixing stuff just to fix it once again when they decide to change something later. Perhaps I should write down in readme what meteor versions roller supports...

**Comment by maxsupermanhd** [comment]
If it is what you want I can merge it no problem, as long as it does not break compatibility with older versions of meteor and game
https://github.com/maxsupermanhd/meteor-villager-roller/compare/main...molniya0207:meteor-villager-roller:main

**Comment by Lovecrafts-Cat** [comment]
> If it is what you want I can merge it no problem, as long as it does not break compatibility with older versions of meteor and game [main...molniya0207:meteor-villager-roller:main](https://github.com/maxsupermanhd/meteor-villager-roller/compare/main...molniya0207:meteor-villager-roller:main)

This change will affect versions going from 1.19+ as per the dev's explaination, so you don't have to update the 1.18.2 release.

**Comment by maxsupermanhd** [comment]
The main point that I want to achieve is to be able to compile mod directly to 1.19 and 1.18.2 at the same time having only one branch effectively. Does this change break any backwards compatibility?

**Comment by Lovecrafts-Cat** [comment]
Hm... I'd think so, since pushing this change to the 1.18.2 release would break it.
The devs won't backtrack to go and change the code of an older release, since it's not in active development.

**Comment by maxsupermanhd** [comment]
The point is that I **at very least** want to target latest devbuild and latest release of meteor. They are both downloadable from their website and both are "supported". I don't care about how they are supported and what do they do to the client but if they break compatibility between release and a dev build (latest release was ages ago just to note) they at least shall break it in the way that it will still run on release, well, because it is a release afterall.

I simply do not understand why those changes have to be made in the first place, `MeteorAddon` class override is literally pointless. I am sorry, not a java expert here but this just frustrates me, why **just one I am feeling lucky google search solves everything?** Why superclass method can't do this: `this.getClass().getCanonicalName()`? Why each and every addon developer must go and change 3 lines of code just so it is able to report a package and class name at runtime?!

I understand changes that actually matter and do something like a version semantics change to a tag dash snapshot, that is completely fine with me. HUD changes are ... debatable but I am not gonna bother, it is better even for the cost of complexity, I agree with them too.

Please @seasnail8169, explain me a java noob why should I even bother and why can not you keep everything simple? I think it was you who said that my mod is great and I did a good job and that's what I get after that?

**Comment by Lovecrafts-Cat** [comment]
In the meantime, you could just make two branches, one for 1.18.2 and one for 1.19.
You don't even have to maintain the 1.18.2 one since it's the stable one. Someday it will go out of support anyways since 1.19 will become the stable release.

Also, dev builds are exactly meant for changes, and they can include breaking ones. You should expect that from a build that isn't yet stable.

As for the reason why the devs chose to implement these changes, you're gonna have to wait for a response from them.

**Comment by seasnail8169** [comment]
I don't really know what you want me to say. Breaking changes happen between releases... You can still use 1.18 addons on 1.18 (release) Meteor. There is absolutely nothing stopping you from creating a branch or release that supports 1.18 Meteor with only a couple of changes. 

The reason I chose for users to provide the package manually is that I don't trust that mods will always put the client entry point of their mod in the base package.

**Comment by seasnail8169** [comment]
Idk why you are saying "that's what I get after that". Breaking changes happen between major versions, its literally the point of semantic versioning. We are allowed to improve our own code. Also the point still stands that 1.18 addons work on 1.18 Meteor. The user can't expect to be able to use the same mod version across multiple mc versions. Sure since addons are much simpler its more likely that they will work, but it doesn't mean we are wrong to implement breaking changes across versions. 

Also, the changes were made solely to *improve* the ease for addon developers. None of those changes effect the end user, but they make things easier for developers to use the addon system. Plus you literally need to change like a few lines to make it work.
